---
title: "Methodolgy"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### The Origins

This is a direct implementation of Drew Linzer’s [dynamic Bayesian forecasting model](https://votamatic.org/wp-content/uploads/2013/07/Linzer-JASA13.pdf). This makes it similar at its core to The Economist’s [presidential forecast](https://projects.economist.com/us-2020-forecast/president) as well as the [2016 election model](https://www.slate.com/features/pkremp_forecast/report.html) by Pierre-Antoine Kremp for Slate.

The model uses the [Fair model](https://fairmodel.econ.yale.edu/RAYFAIR/PDF/2007A.pdf), developed by Yale economist Ray Fair, as its informative Bayesian prior, $h_i$ for states $i=1 … 50$. The Fair model takes into account incumbency, the state of the economy and whether or not the incumbent party has been in office for two or more consecutive terms in order to predict the vote share for both parties. 

### How polls are interpreted

For each poll, the number of respondents declaring that they will vote for Joe Biden ($y_k$) is drawn from a binomial distribution where $i[k]$ and $j[k]$ indicate the state, $i$, and day, $j$, of poll $k$ and $n_k$ denotes the total number of respondents who indicate a preference for one of the two major parties:

$$y_k \sim Binomial(\pi_{i[k]j[k]}, n_k)$$

As this is a direct implementation of Linzer’s model it only takes into account  state polls of “Likely Voters” and ignores national polls as well as polls of “Registered Voters”. It also does not take into account house effects or other sources of survey error like other, more advanced, models do. 

### How latent voter intention is estimated

The daily trends in all states latent voter intention $\pi_{ij}$ are estimated simultaneously as a function of two components: a state-level component, $\beta_{ij}$, and a national-level component, $\delta_j$, that detect systematic departures from $\beta_{ij}$ due to events that affect all states, such as convention bounces. Both components are placed on the logit scale:

$$\pi_{ij} = logit^{-1}(\beta_{ij} + \delta_j) $$


### How the forecast is made

On election day ($\delta_j$) is fixed at 0 and ($\beta_{ij}$) is defined as a Normal distribution around the structural forecast $h_i$. The covariance matrix (a slight departure from Linzer’s initial paper) is set at variance of 0.18 and covariance of 0.162. This ensures that state scores are correlated with each other, since it is highly unlikely that Biden will perform better in Texas than Virginia, something an independent prior would not take into account. 

$$\beta_{iJ} \sim Multivariate Normal(logit(h_i), \Sigma_{end})$$

When predicting the election result weeks or months in advance, there will inevitably be a gap in the polling data. In order to bridge this gap, as well as smoothing voter intention on days no polls are conducted, both the state and national level component use a Bayesian reverse random-walk prior which begins on election day.

Each day’s estimation of $\beta_{ij}$ is given prior distribution:

$$\beta_{ij}|\beta_{ij+1} \sim MultivariateNormal(\beta_{ij+1}, \Sigma_{walk})$$

Similarly, $\delta_j$ is given a prior distribution:

$$\delta_j|\delta_{j+1} \sim MultivariateNormal(\delta_{j+1}, \Sigma_{walk})$$

The variance is also give as $\Sigma_{walk}$ with variance = $0.017^2$ and covariance = 0.0002601.

### What the forecast is doing

Overall, the election day forecast in each state is a compromise between the structural model, $h_i$, and the most recent poll result. The uncertainty depends on the number and size of the polls available as well as the proximity to election day. As older state polls are replaced by newer ones they have less influence on the forecast but they leave behind historical trends in the latent voter intention.

Finally, the electoral vote distribution for Joe Biden is then determined by the probability that Biden’s vote share will be greater than 50% in any given state. 
